name: psdk_bluetooth_ble
description: BLE bluetooth device
version: 0.1.4
repository: https://github.com/prtmax/psdk-examples
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  psdk_bluetooth_traits: ^0.1.4
  psdk_device_adapter: ^0.1.4
  collection: ^1.19.1
  flutter_blue_plus: ^2.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.28.0
