name: bluetooth_ble
description: BLE bluetooth device
version: 0.1.4
repository: https://github.com/prtmax/psdk-examples
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  universal_ble: ^1.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.28.0
